// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminUser = "admin_user"

// AdminUser 管理员后台用户表
type AdminUser struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键-管理员Id表" json:"id"` // 主键-管理员Id表
	Name       string `gorm:"column:name;not null;comment:名字" json:"name"`                         // 名字
	NickName   string `gorm:"column:nick_name;not null;comment:昵称" json:"nick_name"`               // 昵称
	Mobile     string `gorm:"column:mobile;not null;comment:手机号码" json:"mobile"`                   // 手机号码
	LarkOpenID string `gorm:"column:lark_open_id;not null;comment:飞书OpenId" json:"lark_open_id"`   // 飞书OpenId
	Password   string `gorm:"column:password;not null;comment:密码" json:"password"`                 // 密码
	/*
		1：正常
		-1：禁用
	*/
	Status   int32     `gorm:"column:status;not null;default:1;comment:1：正常\n-1：禁用" json:"status"`
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy int64     `gorm:"column:update_by;not null;default:1" json:"update_by"`
	/*
		3：其他
		2：女
		1：男
	*/
	Sex      int32 `gorm:"column:sex;not null;default:3;comment:3：其他\n2：女\n1：男" json:"sex"`
	IsDelete int32 `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
